language: node_js

node_js:
  - '10'
  - '8'
  - '6'

script:
  - node --version
  - npm --version
  - npm run link
  - npm run boot
  - npm run lint
  - npm test

git:
  depth: 5

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
